### ISSUE TITLE
Typo when trying to flag a discovered cell

### ISSUE THREAD

**Issue by Fenho** [IIC3745-Grupo-5/ProyectoA#13]
It says "Cannot **flagged** a discovered cell". It should read something like "Cannot **flag** a discovered cell" or "Cannot **make** a discovered cell **flagged**.
![image](https://user-images.githubusercontent.com/32397663/135281165-bdfb8840-2aa7-4e11-8135-a134e4bcf961.png)

**Comment by dasolari** [comment]
Is this fixed?

**Comment by Fenho** [comment]
Nope. I will be fix now.
