### ISSUE TITLE
When I put a letter as input in row/column the game discover the [0,0] cell

### ISSUE THREAD

**Issue by Meaylwin** [IIC3745-Grupo-5/ProyectoA#14]
I don't know if this is the desired behavior, but when I put a letter as input in row/column the game **always** discover the [0,0] cell. Even if the cell was discovered before.
![image](https://user-images.githubusercontent.com/14930275/135286437-33ce0e23-d1a7-47e8-a7f0-9fe4ef8c5442.png)

**Comment by IriSalazar** [comment]
Let me check that this afternoon. I'll fix it

**Comment by IriSalazar** [comment]
Yes. When the input is a letter de [0,0] is discovered. I'll work on this now

**Comment by IriSalazar** [comment]
Bug fixed in commit 9cdc0f3.
Still missing testing.
