### ISSUE TITLE
[BUG] Winning conditions

### ISSUE THREAD

**Issue by IriSalazar** [IIC3745-Grupo-5/ProyectoA#18]
Even though the player has discovered every empty or numerical cell, he still hasn't won the game. Because the condition to win is to put flags on top of every cell with a bomb. 

![image](https://user-images.githubusercontent.com/26166202/135329013-ee65da35-cb88-471f-8513-6f013cd8936f.png)

The condition to win the game should be to discover every single cell without a bomb.

**Comment by Meaylwin** [comment]
You are right, the rule to win was wrongly defined.
The condition to win is all safe cells be discovered
It will be fixed soon

**Comment by Meaylwin** [comment]
This was solved in the commit 0cb62ba
