### ISSUE TITLE
Game keeps going even if one discovers a mine 💣 

### ISSUE THREAD

**Issue by dasolari** [IIC3745-Grupo-5/ProyectoA#20]
**Describe the bug**
When playing and discovering a mine, the game tells me I discovered one but keeps going, allowing me to keep discovering cells.

**¿How to repeat the bug?**
1. Play the game until you encounter a mine.
2. Keep playing until you win.

**Expected behavior**
The game should notify me that I lost, should not let me choose more cells to discover and should reveal all the mines in the game.

**Additional Context**
Here are some screenshots:
![Screen Shot 2021-10-01 at 10 39 42](https://user-images.githubusercontent.com/42161460/135630817-3f035f54-daff-4568-8f81-2f08bf9ad2a2.png)
![Screen Shot 2021-10-01 at 10 39 54](https://user-images.githubusercontent.com/42161460/135630825-0574a006-49de-418b-9394-2c6bb843cdee.png)

**Comment by Fenho** [comment]
You are right, the feature is actually missing a bunch of things. I am working on it right now.

**Comment by Fenho** [comment]
Issue resolved in the pr #23

**Comment by dasolari** [comment]
Nice, thanks!
