### ISSUE TITLE
Cell has UI elements hardcoded

### ISSUE THREAD

**Issue by Fenho** [IIC3745-Grupo-5/ProyectoA#21]
I am not sure if it is ok or not, but the class Cell is getting a harcoded type:
(cell.rb)
![image](https://user-images.githubusercontent.com/32397663/135635357-506b2bf7-68de-4303-906d-ea8fee6340ac.png)
(cell_type.rb)
![image](https://user-images.githubusercontent.com/32397663/135635490-4a74168e-6824-4f5e-913c-28291a2d4235.png)

This emojis are a part of the UI so maybe this should not be hardcoded text in a class that does not have that responsability.

**Comment by dasolari** [comment]
I'll refactor it as soon as I can.

**Comment by dasolari** [comment]
I just realized that it doesn't look like a good practice at first, but it actually helps to improve code readability, so i'm leaving it the way it is now.
