### ISSUE TITLE
Last cell Exception

### ISSUE THREAD

**Issue by Fenho** [IIC3745-Grupo-5/ProyectoA#32]
If I try to discover the cell from the last row and column, and this cell is neither a mine or a number above 0 (I am assuming this last part because of trial and error), an exception is thrown.
![image](https://user-images.githubusercontent.com/32397663/135783976-963239cf-039b-4550-bbba-fd6f2aad3921.png)

**Comment by dasolari** [comment]
Yes, I just realized this problem. I'll fix it right away.

**Comment by dasolari** [comment]
Bug fixed!
